# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLG_8DhobYXR0A8jtJOaRXf7mViqlCjl

# חלק 1
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)

"""# חלק 1

בחרנו במערך הנתונים "AI Jobs Posting Trends from 2019-2023".
"""

# a block for understanding the data set structure
df = pd.read_csv('gdrive/My Drive/AI_Job_Posting_Trends.csv')
display(df.head())
display(df.info())
display(df.shape[0])

"""הפיצ'רים המוצגים במערך הנתונים וסוגיהם:

1	job_id	קטגוריאלי (ייחודי)

2	job_title	קטגוריאלי

3	salary_usd נומרי שלם

4	salary_currency	קטגוריאלי

5	experience_level	קטגוריאלי (אורדינלי)

6	employment_type	קטגוריאלי

7	company_location	קטגוריאלי

8	company_size	קטגוריאלי (אורדינלי)

9	employee_residence	קטגוריאלי

10	remote_ratio	נומרי שלם

11	required_skills	טקסט חופשי (רשימה)

12	education_required	קטגוריאלי	(אורדינלי)

13	years_experience	נומרי שלם

14	industry	קטגוריאלי

15	posting_date	תאריך (טקסט)

16	benefits_score	נומרי ממשי

17	company_name	קטגוריאלי

18	remote_category	קטגוריאלי	(אורדינלי)

מספר הרשומות במערך הנתונים: 50,000

# חלק 2

עיבוד מקדים של הנתונים לצורך ניתוח בשלבים הבאים:
"""

# Skills preprocessing:
# 1) Tokenize (comma-separated → list)
def to_list(s):
    parts = [p.strip() for p in s.split(",") if p.strip()]
    seen, out = set(), []
    for p in parts:
        if p not in seen:
            out.append(p); seen.add(p)
    return out
df["skills_list"] = df["required_skills"].map(to_list)

# 2) Get top skills
skills_long = df[["job_id", "skills_list"]].explode("skills_list").dropna()
skill_counts = skills_long["skills_list"].value_counts()
top_skills = skill_counts.index.tolist()

# 3) One-hot for the top-N skills
for skill in top_skills:
    df[skill] = df["skills_list"].apply(lambda lst: int(skill in lst))


# Encode experience_level (example order: Entry < Mid < Senior < Executive)
experience_map = {
    "Entry_Level": 1,
    "Mid": 2,
    "Senior": 3,
    "Executive": 4
}
df["experience_level_encoded"] = df["experience_level"].map(experience_map)

# Encode remote_category (example order: On Site < Hybrid < Fully Remote)
remote_map = {
    "On-site": 1,
    "Hybrid": 2,
    "Fully Remote": 3,
}
df["remote_category_encoded"] = df["remote_category"].map(remote_map)

# Encode education_required (example order: Associate < Bachelor < Master < PhD)
education_map = {
    "Associate": 1,
    "Bachelor": 2,
    "Master": 3,
    "PhD": 4
}
df["education_required_encoded"] = df["education_required"].map(education_map)
display(df.head())

"""וויזואליזציות של נתונים שבחרנו להציג:

התפלגות מיומנויות נדרשות:
"""

# 1) Required skills (bar chart)
skills = skill_counts.head(50).reset_index()
skills.columns = ["skill","count"]
sns.barplot(data=skills, x="count", y="skill", color="teal" )
plt.title("Required Skills")
plt.xlabel("Number of job postings")
plt.ylabel("Skill")
plt.show()
top24 = top_skills[:-5]

"""התפלגות תעשיות:"""

# 2) Industries distribution (bar chart)
industries = df["industry"].value_counts().reset_index()
industries.columns = ["industry", "count"]
sns.barplot(
    data=industries,
    x="count",
    y="industry",
    color="darkblue" )
plt.title("Industries Distribution")
plt.xlabel("Number of job postings")
plt.ylabel("Industry")
plt.show()

"""התפלגות שכר (USD):"""

# 3) Salary distribution histogram
sns.histplot(
    data=df['salary_usd'],
    bins=100,
    color="darkcyan"
)
plt.title("Salary Distribution")
plt.xlabel("Salary (USD)")
plt.ylabel("Number of job postings")
plt.show()

"""התפלגות רמת ניסיון:"""

# 4) Experience level distribution
exp_counts = df["experience_level"].value_counts().reset_index()
exp_counts.columns = ["experience_level", "count"]

sns.barplot(
    data=exp_counts,
    x="count",
    y="experience_level",
    hue="experience_level",
    palette="mako",
    legend=False
)
plt.title("Experience Level Distribution")
plt.xlabel("Number of job postings")
plt.ylabel("Experience Level")
plt.show()

"""התפלגות רמת השכלה:"""

# 5) Education required distribution
exp_counts = df["education_required"].value_counts().reset_index()
exp_counts.columns = ["education_required", "count"]

sns.barplot(
    data=exp_counts,
    x="count",
    y="education_required",
    hue="education_required",
    palette="rocket",
    legend=False
)
plt.title("Education Required Distribution")
plt.xlabel("Number of job postings")
plt.ylabel("Education Required")
plt.show()

"""קשר בין מיומנויות לתעשיות:"""

# 1) Skills vs. Industry (heatmap of percentages)
skills_for_heatmap = top24

# Melt to long format
skills_industry = df.melt(
    id_vars=["industry"],
    value_vars=skills_for_heatmap,
    var_name="skill",
    value_name="has_skill"
)

# Keep only rows where job requires the skill
skills_industry = skills_industry[skills_industry["has_skill"] == 1]

# Count postings per (skill, industry)
skill_ind_counts = skills_industry.groupby(["skill", "industry"]).size().unstack(fill_value=0)

# Divide each industry column by its total postings (to get percentages)
industry_totals = df["industry"].value_counts()
skill_ind_pct = skill_ind_counts.divide(industry_totals, axis=1) * 100  # percentage

# Plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(skill_ind_pct, cmap="mako", annot=True, fmt=".1f")
plt.title("Top Skills by Industry (% of postings in industry)")
plt.xlabel("Industry")
plt.ylabel("Skill")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

"""קשר בין שכר למיומנויות:"""

# Salary distribution in different skills
salary_col = "salary_usd"
skills_for_salary = top24
skill_salary_data = []

for skill in skills_for_salary:
    # Jobs that require this skill
    skill_jobs = df[df["skills_list"].apply(lambda lst: isinstance(lst, list) and (skill in lst))]
    # Count each job once
    skill_jobs_unique = skill_jobs.drop_duplicates(subset=["job_id"])
    # Keep salary as a DataFrame and tag with the skill name
    temp = skill_jobs_unique[[salary_col]].copy()
    temp["skill"] = skill
    skill_salary_data.append(temp)

# Combine and clean
skills_salary_df = pd.concat(skill_salary_data, ignore_index=True)
skills_salary_df = skills_salary_df.dropna(subset=[salary_col])


plt.figure(figsize=(10, 6))
sns.boxplot(
    data=skills_salary_df,
    x="skill",
    y=salary_col,
    color="darkblue"
)
plt.title("Salary Distribution by Top Skills")
plt.xlabel("Skill")
plt.ylabel("Salary (USD)")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

"""קשר בין רמת השכלה למיומנויות:"""

# Education level distribution in different skills
skills_for_plot = top24

# Calculate average encoded education level for each skill
skill_avg_edu = {}
for skill in skills_for_plot:
    if skill in df.columns:
        # Take only jobs that require this skill
        mask = df[skill] == 1
        avg_val = df.loc[mask, "education_required_encoded"].mean()
        skill_avg_edu[skill] = avg_val

# Convert to DataFrame for plotting
plot_df = pd.DataFrame(list(skill_avg_edu.items()), columns=["Skill", "AvgEducation"])


# Plot
plt.figure(figsize=(8, 5))
sns.barplot(
    data=plot_df,
    x="AvgEducation",
    y="Skill",
    color="purple"
)
plt.title("Average Education Level (1=Assoc, 4=PhD) for Selected Skills")
plt.xlabel("Average encoded education level")
plt.ylabel("Skill")
plt.tight_layout()
plt.show()

"""שלושת הגרפים מציגים ממוצעים מקודדים עבור הכישורים המובילים בשלושה ממדים שונים:
1- השכלה
2- ניסיון
3- עבודה מרחוק

"""

# Experience level distribution in different skills
skills_for_plot = top24

# Calculate average encoded experience level for each skill
skill_avg_exp = {}
for skill in skills_for_plot:
    if skill in df.columns:
        # Take only jobs that require this skill
        mask = df[skill] == 1
        avg_val = df.loc[mask, "experience_level_encoded"].mean()
        skill_avg_exp[skill] = avg_val

# Convert to DataFrame for plotting
plot_df_exp = pd.DataFrame(list(skill_avg_exp.items()), columns=["Skill", "AvgExperience"])

# Plot
plt.figure(figsize=(8, 5))
sns.barplot(
    data=plot_df_exp,
    x="AvgExperience",
    y="Skill",
    color="orange"
)
plt.title("Average Experience Level (1=Entry, 4=Executive) for Selected Skills")
plt.xlabel("Average encoded experience level")
plt.ylabel("Skill")
plt.tight_layout()
plt.show()

# Job "remoteness" degree distribution by skills
skills_for_plot = top24

# Calculate average encoded remote category for each skill
skill_avg_remote = {}
for skill in skills_for_plot:
    if skill in df.columns:
        mask = df[skill] == 1
        avg_val = df.loc[mask, "remote_category_encoded"].mean()
        skill_avg_remote[skill] = avg_val

# Convert to DataFrame for plotting
plot_df_remote = pd.DataFrame(list(skill_avg_remote.items()), columns=["Skill", "AvgRemote"])

# Plot
plt.figure(figsize=(8, 5))
sns.barplot(
    data=plot_df_remote,
    x="AvgRemote",
    y="Skill",
    color="seagreen"
)
plt.title("Average Remote Category (1=On-site, 3=Fully Remote) for Selected Skills")
plt.xlabel("Average encoded remote category")
plt.ylabel("Skill")
plt.tight_layout()
plt.show()

"""# חלק 3

בדיקת השערות על השאלה שלנו באמצעות bootstrap.
"""

def bootstrap_mean(sample, mask, col_name, num_replications):
    sample_mask = mask.loc[sample.index]
    with_skill = sample.loc[sample_mask, col_name].dropna().reset_index(drop=True)
    without_skill = sample.loc[~sample_mask, col_name].dropna().reset_index(drop=True)
    sample_size_with = with_skill.shape[0]
    sample_size_without = without_skill.shape[0]
    bootstrap_means = np.empty(num_replications)
    for i in range(num_replications):
        bootstrap_sample_with = with_skill.sample(sample_size_with, replace=True)
        bootstrap_sample_without = without_skill.sample(sample_size_without, replace=True)
        bootstrap_means[i] = bootstrap_sample_with.mean() - bootstrap_sample_without.mean()
    return bootstrap_means

# בחירת מיומנות לבדיקה: הכי נפוצה שיש לה שתי קבוצות מספיק גדולות
min_per_group = 50
top_skill = None
for s in top_skills:
    if s in df.columns:
        m = (df[s] == 1)
        if m.sum() >= min_per_group and (~m).sum() >= min_per_group:
            top_skill = s
            break
if top_skill is None:
    top_skill = top_skills[0]
print(f"מיומנות נבדקת: {top_skill}")

col_name = "salary_usd"
tested_skill_mask = (df[top_skill] == 1)
NUM_REP = 10000
sample = df.sample(n=50000, random_state=42)
means_bootstrapped = bootstrap_mean(sample, tested_skill_mask, col_name, NUM_REP)
# CI אחוזוני 95% להפרש
ci_lower, ci_upper = np.percentile(means_bootstrapped, [2.5, 97.5])
print(f"רווח הסמך ברמת מובהקות של 95%: [{ci_lower:.2f}, {ci_upper:.2f}]")

mean_with    = df.loc[tested_skill_mask,  col_name].dropna().mean()
mean_without = df.loc[~tested_skill_mask, col_name].dropna().mean()
param_mean = mean_with - mean_without

# תצוגה של היסטוגרמת ההתפלגויות של הפרש הממוצעים
fig, ax = plt.subplots()
ax.hist(means_bootstrapped, bins=40, edgecolor='black', linewidth=0.6)
# רווח הסמך - הקו הכתום
ax.hlines(y=0, xmin=ci_lower, xmax=ci_upper, colors='orange', linestyles='solid', linewidth=6, zorder=5, clip_on=False)
# סימון ערך הפרמטר האמיתי
ax.scatter([param_mean], [0], c='red', s=200, zorder=6, clip_on=False)
ax.set_title("Bootstrap Distribution of Difference in Salary Means")
ax.set_xlabel("Difference in Means (USD)")
ax.set_ylabel("Frequency")
fig.tight_layout()
plt.show()

"""# Part 4

קלאסטרינג על הפיצ'רים שבחרנו
"""

# Build features: Education + Experience + Remote
skills_for_clustering = top24

def standard_scale(df_in: pd.DataFrame):
    df = df_in.copy()
    means = df.mean(axis=0)
    stds = df.std(axis=0).replace(0, np.nan)  # avoid divide-by-zero
    return ((df - means) / stds).fillna(0.0)

# Compute per-skill averages for the three features
skill_avg_edu = {
    s: df.loc[df[s] == 1, "education_required_encoded"].mean()
    for s in skills_for_clustering if s in df.columns
}
skill_avg_exp = {
    s: df.loc[df[s] == 1, "experience_level_encoded"].mean()
    for s in skills_for_clustering if s in df.columns
}
skill_avg_remote = {
    s: df.loc[df[s] == 1, "remote_category_encoded"].mean()
    for s in skills_for_clustering if s in df.columns
}

# Create the feature table (three columns)
avg_df = pd.DataFrame({
    "AvgEducation": pd.Series(skill_avg_edu),
    "AvgExperience": pd.Series(skill_avg_exp),
    "AvgRemote": pd.Series(skill_avg_remote),
}).loc[skills_for_clustering]

# Scale to mean=0, std=1
km_scaled_df = standard_scale(avg_df)


# Numpy matrix for KMeans
X = km_scaled_df.values

print("Final features shape (should be N_skills x 3):", km_scaled_df.shape)
km_scaled_df.head()

"""בטבלה המוצגת לעיל מוצגים הפיצ'רים שנבחרו כקלט לאלגוריתם האשכול, ובהם נשתמש לצורך ביצוע הקלאסטרינג.

בחירת ערך של K:
"""

# Elbow method

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

sse = []
K_range = range(2, 20)  # Try different K values

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(km_scaled_df)
    sse.append(kmeans.inertia_)  # Inertia = sum of squared distances to cluster centers

# Plot Elbow curve
plt.figure(figsize=(6, 4))
plt.plot(K_range, sse, marker='o')
plt.title("Elbow Method for Optimal K")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Sum of squared distances (Inertia)")
plt.grid(True)
plt.show()

# Run KMeans with chosen K
k_optimal = 6  # from elbow or decision

km = KMeans(n_clusters=k_optimal, random_state=42, n_init=10)
km.fit(km_scaled_df)

# Cluster centers (scaled space)
cluster_centers = km.cluster_centers_
labels = km.labels_

print("Cluster Centers Shape:", cluster_centers.shape)
print("Labels array:", labels)

# Assign clusters back to skills
df_clusters = km_scaled_df.copy()
df_clusters["Cluster"] = labels
df_clusters.index.name = "Skill"

# Optional: sort by cluster for readability
df_clusters_sorted = df_clusters.sort_values("Cluster")

df_clusters_sorted.head()

"""קלאסטרינג על שלושת הפיצ'רים ביחד:"""

# 3D visualization: Education × Experience × Remote

from mpl_toolkits.mplot3d import Axes3D  # needed for 3D projection

labels = km.labels_
k = km.n_clusters
cluster_colors = plt.cm.tab10(np.linspace(0, 1, max(10, k)))[:k]

fig = plt.figure(figsize=(7.5, 6.5))
ax = fig.add_subplot(111, projection='3d')
fig.suptitle("K-Means on AvgEducation × AvgExperience × AvgRemote (scaled)", y=0.98)

# Points per cluster
for cl in range(k):
    m = (labels == cl)
    ax.scatter(
        km_scaled_df.loc[m, "AvgEducation"],
        km_scaled_df.loc[m, "AvgExperience"],
        km_scaled_df.loc[m, "AvgRemote"],
        s=60, color=cluster_colors[cl], alpha=0.9, label=f"Cluster {cl}"
    )

# Centroids
C = km.cluster_centers_
ax.scatter(
    C[:, 0], C[:, 1], C[:, 2],
    marker='*', s=320,
    c=[cluster_colors[cl] for cl in range(k)],
    edgecolor='black', linewidths=0.8
)

ax.set_xlabel("AvgEducation (scaled)")
ax.set_ylabel("AvgExperience (scaled)")
ax.set_zlabel("AvgRemote (scaled)")

# Legend above plot in one line
handles = [plt.Line2D([0],[0], marker='o', linestyle='', color=cluster_colors[cl], label=f"Cluster {cl}") for cl in range(k)]
fig.legend(handles=handles, loc="upper center", ncol=min(k, 10), frameon=False, bbox_to_anchor=(0.5, 1.02))

plt.tight_layout()
plt.show()

"""ייצוג גרפי של כל מישור - XY, XZ, YZ עבור הגרף התלת ממדי"""

# 2D plots for (Edu, Exp, Remote)
pairs = [
    ("AvgEducation", "AvgExperience"),
    ("AvgEducation", "AvgRemote"),
    ("AvgExperience", "AvgRemote"),
]

fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))
for i, (fx, fy) in enumerate(pairs):
    ax = axes[i]
    for cl in range(k):
        m = (labels == cl)
        ax.scatter(
            km_scaled_df.loc[m, fx],
            km_scaled_df.loc[m, fy],
            s=60, color=cluster_colors[cl], alpha=0.85,
            label=f"Cluster {cl}" if i == 0 else None
        )
        # centroid for this pair (same color)
        ax.scatter(
            km.cluster_centers_[cl, km_scaled_df.columns.get_loc(fx)],
            km.cluster_centers_[cl, km_scaled_df.columns.get_loc(fy)],
            marker='*', s=250, color=cluster_colors[cl],
            edgecolor='black', linewidths=0.7, zorder=5
        )
    ax.set_xlabel(fx)
    ax.set_ylabel(fy)
    ax.set_title(f"{fx} vs {fy}")

# one shared legend above
handles = [plt.Line2D([0],[0], marker='o', linestyle='', color=cluster_colors[cl], label=f"Cluster {cl}") for cl in range(k)]
fig.suptitle("K-Means clusters across selected feature pairs", y=1.03, fontsize=13)
fig.legend(handles=handles, loc="upper center", ncol=min(k, 10), frameon=False, bbox_to_anchor=(0.5, 1.02))

plt.tight_layout()
plt.show()

"""קלאסטרינג על זוגות שונים של פיצ'רים:"""

# K-Means on PAIRS of features (Edu/Exp/Remote)

pairs = [
    ("AvgEducation", "AvgExperience"),
    ("AvgExperience", "AvgRemote"),
    ("AvgEducation", "AvgRemote"),
]

def standard_scale(df):
    m, s = df.mean(0), df.std(0).replace(0, np.nan)
    return ((df - m) / s).fillna(0.0)

# Elbow plots for each pair
for fx, fy in pairs:
    print(f"\n Pair: {fx} vs {fy} ")

    df_pair_sc = standard_scale(avg_df[[fx, fy]])

    sse, K_range = [], range(2, 20)
    for k in K_range:
        km_tmp = KMeans(n_clusters=k, random_state=42, n_init=10)
        km_tmp.fit(df_pair_sc)
        sse.append(km_tmp.inertia_)

    plt.figure(figsize=(6, 4))
    plt.plot(K_range, sse, marker='o')
    plt.title(f"Elbow Method for {fx} vs {fy}")
    plt.xlabel("Number of Clusters (K)")
    plt.ylabel("Sum of squared distances (Inertia)")
    plt.grid(True)
    plt.show()

# Plot all pairs in one figure
k_optimal = 6  # Picked from elbow inspection
colors_fn = lambda k: plt.cm.tab10(np.linspace(0, 1, max(10, k)))[:k]

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
axes = np.atleast_1d(axes)

for ax, (fx, fy) in zip(axes, pairs):
    df_pair_sc = standard_scale(avg_df[[fx, fy]])

    km = KMeans(n_clusters=k_optimal, random_state=42, n_init=10).fit(df_pair_sc)
    labels, centers = km.labels_, km.cluster_centers_
    cols = colors_fn(k_optimal)

    for cl in range(k_optimal):
        mask = (labels == cl)
        ax.scatter(df_pair_sc.iloc[mask, 0], df_pair_sc.iloc[mask, 1],
                   s=60, alpha=0.9, color=cols[cl],
                   label=f"Cluster {cl}" if ax is axes[0] else None)
        ax.scatter(centers[cl, 0], centers[cl, 1],
                   marker='*', s=280, color=cols[cl],
                   edgecolor='black', linewidths=0.8, zorder=5)
        ax.text(centers[cl, 0], centers[cl, 1], f"  {cl}",
                fontsize=9, weight='bold', va='center')

    ax.set_xlabel(f"{fx} (scaled)")
    ax.set_ylabel(f"{fy} (scaled)")
    ax.set_title(f"{fx} vs {fy} (k={k_optimal})")
    ax.grid(True, alpha=0.25)
    for spine in ax.spines.values():
        spine.set_alpha(0.3)

# Legend & layout
handles, labels_legend = axes[0].get_legend_handles_labels()
fig.suptitle("K-Means clusters on pairs of features (scaled)", y=1.03, fontsize=14)
fig.legend(handles, labels_legend, loc="upper center",
           ncol=min(len(handles), 10), frameon=False, bbox_to_anchor=(0.5, 1.01))

plt.show()